name: Run Calculator
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-calculator:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run calculator
        run: python calculator.py